//there are 120 strings in this block
//remember to set the origin before calling this file

Text("Flower Crown")
Text("Dragon Crown")
Text("Gold Crown")
Text("Horns")
Text("Arr") //Arrow
Text("Ribbon")
Text("Bunny Ears")
Text("Tiara")
Text("Devil Wings Jewelry")
Text("Incense Stick")
Text("White Hat")
Text("Blue Cap")
Text("Top Hat")
Text("Dark Knight Jewelry")
Text("Colorful Pendant")
Text("Pink Glasses")
Text("Dragon Mask")
Text("Gold Mask")
Text("Dark Knight Mask")
Text("Electric Glasses")
Text("Hypno Glasses")
Text("Sunglasses")
Text("Zamasu Glasses")
Text("Ancient Mask")
Text("Monacle") //Detective
Text("Transform Set")
Text("Pipe")
Text("Wealthy Beard")
Text("Dark Gaiter")
Text("Pig Nose")
Text("Beaded Necklace")
Text("Warrior Amulet")
Text("Jewel Necklace")
Text("Skull Necklace")
Text("Dogtag")
Text("Polka Dot Tie")
Text("Dragon Chestplate")
Text("Prince Chestplate")
Text("Dark Knight Chestplate")
Text("Front Armor")
Text("Frilly Lace")
Text("Emblem")
Text("Lion Mask")
Text("Devil Mask")
Text("Gauge")
Text("Angel Wings")
Text("Dragon Wings")
Text("Hawk Wings")
Text("Devil Wings")
Text("School Bag")
Text("Cute Cape")
Text("Knight Cape")
Text("Prince Cape")
Text("Dark Knight Cape")
Text("Wind-Up Key")
Text("Angel Butterfly")
Text("Hero's Cape")
Text("Gold Butterfly")
Text("Ribbon")
Text("Helicopter")
Text("Head: A good-smelling crown made of grass.")
Text("Head: A crown taken from a legendary dragon.")
Text("Head: A crown made from a noble omen.")
Text("Head: Two pieces taken from a strange animal.")
Text("Head: A mysterious headpiece that doesn't hurt.")
Text("Head: A big, cute pink ribbon.")
Text("Head: Two pointy bunny ears.")
Text("Head: A very cute hair ornament with a heart.")
Text("Head: A black devil's ear and a black badge.")
Text("Head: A summer sheep's gift with a swirl.")
Text("Head: A plastic hat with a pink band on the ground.")
Text("Head: A blue cap with a swirl on it.")
Text("Head: A black proof of Pointy Hat's defeat.")
Text("Head: A decoration that increases strength.")
Text("Head: A rainbow-colored fake mohawk.")
Text("Face: A pink frame that is used as an accent.")
Text("Face: A mask taken from a legendary dragon.")
Text("Face: A golden mask passed down.") //though generations
Text("Face: A dark mask that increases power.")
Text("Face: Popular glasses with a bright light on the edges.")
Text("Face: Funny glasses that spin in a swirl pattern.")
Text("Face: Black sunglasses used by police.")
Text("Face: Red intellectual glasses with a raised edge.")
Text("Face: A mask used in ancient festivals.")
Text("Face: Warrior glasses that only allow one eye to see.")
Text("Face: Party goods with glasses, a nose, and a beard.")
Text("Face: Wooden pipe and a mustache.")
Text("Face: A large, fluffy white beard.")
Text("Face: Black eyeshadows that look like an animal.")
Text("Face: A cute pig-shaped eyeshadow.")
Text("Chest: A necklace made of blue and pink beads.")
Text("Chest: A warrior's token that inspires courage.")
Text("Chest: A ring of many large pearls.")
Text("Chest: A necklace with a skull on the breast.")
Text("Chest: A cherry blossom amulet.")
Text("Chest: A flashy bow tie with white beads.")
Text("Chest: A breastplate taken from a dragon.")
Text("Chest: A royal breastplate painted red by gold.")
Text("Chest: Powerful breast armor.")
Text("Chest: A large keyhole for a big guard.")
Text("Chest: A white dog hanging against the chest.")
Text("Chest: A sign of a clean house.")
Text("Chest: A gold lion hanging against") //the chest.")
Text("Chest: A chest adornment with a black face.")
Text("Chest: A meter that shows lots") //many things.")
Text("Back: White wings of a new angel.")
Text("Back: Wings of a legendary dragon.")
Text("Back: Big brown hawk wings.")
Text("Back: Black wings of a black monster.")
Text("Back: A brand new red backpack.")
Text("Back: A cute cape with yellow letters and pink hearts.")
Text("Back: A tall blue cape with a hood.")
Text("Back: A basic cape filled with golden food.")
Text("Back: A dark cape imbued with power.")
Text("Back: A big spring attached to the back.")
Text("Back: A simple white butterfly feather.")
Text("Back: A red burning justice cape.")
Text("Back: A gold swallowtail butterfly feather.")
Text("Back: A big orange ribbon attached to the back.")
Text("Back: A dreamy helicopter feather attached to the back.")
