//there are 398 strings in this block
//remember to set the origin before calling this file

Text("Escape successful!")
Text("Escape failed")
Text("%s damage")
Text("Critical hit!")
Text("Weak spot!")
Text("No damage!")
Text("Dodged")
Text("No effect")
Text("Blocking")
Text("Not enough Power!")
Text("Paralyzed!")
Text("Deep asleep...")
Text("%s Poison damage")
Text("%s Potent poison damage")
Text("%s Magma damage")
Text("%s Electric damage")
Text("Couldn't chant spell!")
Text("Couldn't chant spell properly!")
Text("Confused")
Text("Staring blankly")
Text("Knocked unconscious")
Text("%s has fallen")
Text("Revival failed")
Text("Life -%D")
Text("Power -%D")
Text("Stole %D Life")
Text("Stole %D Power")
Text("Stole %D Boru")
Text("Stole %s")
Text("Nothing to steal")
Text("Didn't steal anything")
Text("Used %s, but nothing happened")
Text("Used %s")
Text("Out of items")
Text("Weapon unequipped")
Text("Shield unequipped")
Text("Acc. unequipped")
Text("Couldn't unequip")
Text("Barrier gone")
Text("Barrier used")
Text("Spell reflected!")
Text("Spell deflected!")
Text("Spell diffused!")
Text("Spell widely diffused!")
Text("Covered in a dark veil")
Text("Dark veil has dissipated")
Text("Reached hand") //fix with proper term
Text("Couldn't Hold Hands")
Text("Couldn't reach out") //fix with proper term
Text("Can't Hold Hands")
Text("Hands full")
Text("Can't connect to leader")
Text("No one was there")
Text("Already Holding Hands")
Text("Golems can only Hold Hands with you")
Text("Can't carry while Holding Hands")
Text("Can't carry that")
Text("Can't Hold Hands while carrying")
Text("Can't Hold Hands")
Text("Couldn't do it")
Text("Have not bonded yet")
Text("Hold Hands undone!")
Text("Released Hand")
Text("Can't invert Hands")
Text("Attack")
Text("Block")
Text("Melted %I")
Text("Not equipped with sword")
Text("Can't use while conscious")
Text("Can't use here")
Text("Untransformed!")
Text("Gotcha!")
Text("Smelly gel!")
Text("Sticky gel!")
Text("Sour gel!")
Text("Fire breath!")
Text("Scorching breath!")
Text("Icy breath!")
Text("Earth-shaking roar!")
Text("Terrifying roar!")
Text("Roar of strength!")
Text("Copied Strength of\n%s!")
Text("Copied Speed of\n%s!")
Text("Copied Intelligence of\n%s!")
Text("Studied memory of %s!")
Text("But didn't know a spell")
Text("Phase shifted")
Text("Cast a force field")
Text("Isolation beam!")
Text("Awkwardness beam!")
Text("Relaxation beam!")
Text("Block has been dropped!")
Text("Rinse beam!")
Text("Called for allies!")
Text("Reflection barrier!")
Text("Reflection barrier x 2!")
Text("Reflection barrier x 3!")
Text("Deflection barrier!")
Text("Deflection barrier x 2!")
Text("Deflection barrier x 3!")
Text("Cast diffusion field")
Text("Cast super diffusion field")
Text("Sprayed confusion gas!")
Text("Wide sprayed confusion gas!")
Text("Sprayed blinding gas!")
Text("Wide sprayed blinding gas!")
Text("Wide sprayed sleeping gas!")
Text("Wide sprayed silencing gas!")
Text("Wide sprayed poison gas!")
Text("Wide sprayed potent poison gas!")
Text("Shufflie Beam")
Text("Scoochie Beam")
Text("Swappie Beam")
Text("Pullie Beam")
Text("Pushie Beam")
Text("Splittie Beam")
Text("Poison Attack")
Text("Potent Poison")
Text("Fire Attack")
Text("Lightning Attack")
Text("Ice Attack")
Text("Undodgeable Attack")
Text("Blasting Attack")
Text("Slid hands in pocket")
Text("Slid hands in bag")
Text("Slid hands in inventory")
Text("Dimension beam!")
Text("Quad attack!")
Text("Casted speech-restriction!")
Text("Yelled loudly!")
Text("All-erasing light!")
Text("Reflects damage!")
Text("Heat ray!")
Text("Casted a strength-draining curse!")
Text("Offered an evil prayer")
Text("Erupted!")
Text("Thrown flaming boulder!")
Text("Landing earthquake!")
Text("Meteor kick!")
Text("Spinning slash!")
Text("Didn't work")
Text("Duplicated %s")
Text("No more space")
Text("It will cost %s Boru. Continue?")
Text("Couldn't push")
Text("Uho!")
Text("No controller connected to Port 2")
Text("Can't use this now")
Text("Can't use this here")
Text("Not enough Power!")
Text("Failed")
Text("Can't leave friends behind")
Text("Can't do it now")
Text("Can't leave now")
Text("unused")
if (file == CLIENT) {
  Text("Expelled")
}
Text("Didn't budge")
Text("No one to send to")
Text("Used the Blessing of Life")
Text("Special Fire Combo!")
Text("Special Thunder Combo!")
Text("Special Hurricane Combo!")
Text("Couldn't find jump destination")
Text("Powered up with Hold Hands!")
Text("Inherited %s!")
Text("Inherited %d skill!")
Text("Inherited %d characteristics!")
Text("Acquired Fire resistance!")
Text("Acquired Ice resistance!")
Text("Acquired Wind resistance!")
Text("Acquired Electric resistance!")
Text("Acquired Sleep resistance!")
Text("Acquired Poison resistance!")
Text("Inherited Fire resistance!")
Text("Inherited Ice resistance!")
Text("Inherited Wind resistance!")
Text("Inherited Electric resistance!")
Text("Inherited Sleep resistance!")
Text("Inherited Poison immunity!")
Text("Strength Speed Mind increased!")
Text("Inherited Critical Hit chance up!")
Text("Inherited the ability to see the invisible!")
Text("Inherited Electric resistance!")
Text("Inherited poison resistance!")
Text("Found %s treasure")
Text("No treasure")
Text("Radio jammed")
Text("Sent item")
Text("Failed to send")
Text("Escape outside?")
Text("Go back to town?")
Text("Go back to prison?")
Text("Couldn't throw away item")
Text("Weapon")
Text("Shield")
Text("Acc.")
Text("Can't be used near monsters")
Text("Received %s")
Text("Equip %s")
Text("Equip %s")
Text("Removed %s")
Text("Dropped %s")
Text("Press the B Button")
Text("     Sort Items")
Text("Picked up %s!")
Text("Inventory full")
Text("Monster jumped out!")
Text("Trap was sprung!")
Text("Life restored")
Text("Power restored")
Text("Poison cured")
Text("Status effects removed")
Text("Nothing happened")
Text("Nothing came out")
Text("Evaluation up by %s!")
Text("Nothing inside")
Text("Not yet open.\n%d more needed.")
Text("Not yet open.\nOne more!")
Text("Not yet open.\nTwo more.")
Text("Not strong enough to open.")
Text("Someone else is opening it.")
Text("On lights") //fix later
Text("Off lights") //fix later
Text("Courage welled up inside")
Text("Focused courage into sword")
Text("Sword is full of courage")
Text("Not enough experience")
Text("Charge the sword in exchange to experience")
Text("Revive an ally in exchange to experience")
Text("Can't be given") //here; fix later
Text("Can't put away")
Text("Can't be used anymore")
Text("Restored %D")
Text("Completely recovered")
Text("Super energized!")
Text("Power restored by %D")
Text("Lost %D Power")
Text("Learned %s!")
Text("Gained %D exp") //experience; fix later
Text("Lost %D experience")
Text("Leveled up to %D!")
Text("Leveled down to %D!")
Text("Revived!")
Text("Got %D Boru")
Text("Got %D Boru and %D exp") //experience; fix later
Text("%D Boru and %D exp")
Text("Cursed by %D")
Text("Hold Hands curse casted")
Text("Hold Hands lifted")
Text("Waiting..")
Text("Thinking..")
if (file == ALONE) {
  Text("%s's level raised to %D!")
  Text("Life raised by %D")
  Text("Power raised by %D")
}
Text("Str raised by %D") //strength; fix later
Text("Speed raised by %D")
Text("Mind raised by %D")
if (file == ALONE) {
  Text("%s has learned %s!")
}
Text("Became Trembled")
Text("Became Confused")
Text("Movement restricted")
Text("Became Paralyzed")
Text("Fell asleep")
Text("Can see invisible")
Text("Became Blind")
Text("Difficult Hearing")
Text("Hearing recovered")
Text("Became Silenced")
Text("Became Letter-Sealed")
Text("Poisoned!")
Text("Heavily Poisoned!")
Text("Transformed")
Text("Str lowered by %D") //strength; fix later
Text("Speed lowered by %D")
Text("Mind lowered by %D")
Text("No longer Trembled")
Text("No longer Confused")
Text("Movement recovered")
Text("No longer Paralyzed")
Text("No longer Asleep")
Text("No longer Invisible")
Text("No longer See Invisible") //fix later
Text("No longer Blind")
Text("No longer Deaf")
Text("No longer Hearing Disabled")
Text("No longer Silenced")
Text("No longer Sealed")
Text("No longer Poisoned")
Text("No longer Deadly Poisoned")
Text("Strength returned")
Text("Speed returned")
Text("Mind returned")
Text("Not Frightened")
Text("Not Confused")
Text("Not slowed down")
Text("Not asleep") //fix later
Text("Not Blinded")
Text("Not Deafened")
Text("Not Silenced")
Text("Not Letter-Sealed")
Text("Not Poisoned")
Text("Not Deadly Poisoned")
Text("Not Trembled")
Text("Not Deadly Poisoned") //max poison damage; fix later
Text("Cannot be used here")
Text("Movement unrestricted")
Text("Poison removed")
Text("Barrier removed")
Text("All status effects removed")
Text("Now visible") //fix later
Text("Status")
Text("Points")
Text("Items")
Text("Skills")
Text("Speak")
Text("Open")
Text("Examine")
Text("Receive")
Text("Talk")
Text("Team Up")
if (file == CLIENT) {
  Text("Emotion")
}
Text("Retry")
Text("Give up and escape to somewhere safe?")
if (file == ALONE) {
  Text("Give up and try again. (Return to Title)")
}
Text("Do you want to retreat?\nYou'll lose some money.")
if (file == CLIENT) {
  Text("You have been logged out due to inactivity.")
}
Text("Run")
Text("Wait")
Text("You don't have anything.")
Text("Use")
Text("Equip")
Text("Remove")
Text("Toss")
Text("Give")
Text("Exchange")
Text("No bonds have been formed.")
Text("Checking")
Text("Tell everyone")
Text("Tell someone")
Text("Warp nearby")
Text("Break bond")
Text("Break bond with %s?")
Text("Speak to someone privately.")
Text("Move next to player: 40 Power")
Text("Forgot player and removed from book.")
Text("Group forgotten")
Text("Hold Hands")
Text("Let Go")
Text("Hold On")
Text("Buy")
Text("Sell")
Text("Explanation")
Text("Buy in Bulk")
Text("Sell in Bulk")
Text("Is this okay?")
Text("Carrying too many items")
if (file == ALONE) {
  Text("Create")
}
Text("Normal")
Text("Fainted")
Text("Fire Resistant")
Text("Light Resistant")
Text("Wind Resistant")
Text("Electric Resistant")
Text("Slp Resist") //strong to sleep; fix later
Text("Psn Resistant") //poison resistant; fix later
if (file == CLIENT) {
  Text("No HomeLands found.")
  Text("%s HomeLands found.")
  Text("%s HomeLands found, showing the first 50.")
  Text("Enter a password.")
  Text("%2d/%2d") //Players
  Text("%5d Players guided.")
  Text("Starting in %2d")
  Text("%2d:%2d elapsed")
}
Text("Target not found.")
Text("Not owned.")
if (file == CLIENT) {
  Text("Could not see the log.")
  Text("Please check again.")
}
Text("Battle Zoom")
Text("Skill Pointer")
Text("BGM Volume")
Text("SE Volume")
if (file == CLIENT) {
  Text("Stay-Homes")
  Text("After logging out, your mascot will\n remain in this world as a Stay-Home.\nWho may your mascot accompany?")
  Text("Angry")
  Text("Happy")
  Text("Surprised")
  Text("Shocked")
  Text("Sad")
  Text("Panicked")
  Text("Confuse") //d
  Text("Sweaty")
  Text("Add a letter after your name for identification.")
  Text("Is this your name?")
  Text("Cancel entering this HomeLand?")
  Text("This HomeLand is full.")
}
Text("There is an event currently going on\nand you cannot log in.\nPlease wait until it completes.")
if (file == ALONE) {
  Text("[Block Mascot]\nThe folk of toys who live in Apricant Town.\nTheir Life Points are low, but they are quite excellent sorcerers.")
  Text("[Flame Mascot]\nThe folk of flame who live in Kiro Town.\nThey are strong to flame magic, and can share Status Points with others.")
  Text("[Sparkle Mascot]\nThe folk of sparkling jewels who live in Kiro Town.\nThey can make barriers that can reflect all spell effects.")
  Text("[Polka Mascot]\nThe folk of greens who live in Polka Village.\nThey can revive themselves anywhere.")
  Text("[Pinnoc Mascot]\nThe folk of puppets who live in Croats Village.\nThey're good at healing and reviving others and even monsters too.")
  Text("[Eggpot Mascot]\nThe folk of small eggs who live in Eggpot Village.\nThey have extra defense when shut in their shells.")
  Text("[Cyclone Mascot]\nThe folk of cyclone who live in Ilumina Town.\nThey can blow and inhale monsters, and use Wind magic.")
  Text("[Doh Mascot]\nThe folk of clay who live in Kanel Town.\nThey can change their shapes and transform into monsters and things.")
  Text("[Mystica Mascot]\nThe folk of invisibity who live in Croro Ruins. They can turn completely invisible except for their clothes.")
  Text("[Robot Mascot]\nThe folk of robots who created Elza Town long ago.\nThey are good at stealing and copying items from monsters.")
  Text("[Gort Mascot]\nThe folk of buildings who live in Palmalla Town.\nTheir Life are the highest and they strength increasing skills.")
  Text("[Unicorn Mascot]\nThe folk of proud unicorns who live in Valk Town.\nThey are good at using swords and attack quickly.")
  Text("[Tiptap Mascot]\nThe folk of bugs who live in Rainbow's Edge.\nThey can search chests, confuse enemies, and move items.")
  Text("[Paradisa Mascot]\nMysterious squid folk with special eyes.\nTheir Strength Points are the lowest, but have a variety of magic spells.")
  Text("[God Mascot]\nA being of great power who looks down on the world from above.\nThey use special skills to change the world below.")
  Text("There are no mascots here yet.")
  Text("Out on an adventure.")
  Text("Out playing as a god.")
}
Text("Can't talk to this person.")
Text("An event is taking place so you can't enter.\nPlease wait a while.")
Text("The event seems to have ended.")
Text("Cannot leave friends behind.")
Text("It seems to be crowded. Please wait a while.")
Text("unused")
Text("unused")
Text("Could not create a golem!")
Text("No space to create a golem!")
Text("Could not invert order because") //there was a Stay-Home player.")
Text("Could not invert order because") //a player could not move.")
