//there are 80 strings in this block
//remember to set the origin before calling this file

if (file == SERVER) {
  Text("Comment")
  Text("Now")
  Text("10 minutes")
  Text("20 minutes")
  Text("30 minutes")
  Text("40 minutes")
  Text("50 minutes")
  Text("60 minutes")
  Text("< No password >")
  Text("Resetting start time.")
  Text("The play session will be saved and ended shortly. Continue?")
  Text("Are you sure you want to close this HomeLand?")
  Text("Are you sure you want to shut the Ark and open a world?")
  Text("Your HomeLand profile")
  Text("Event Log")
  Text("God Move")
  Text("Decend")
  Text("Ascend")
  Text("Pursue")
  Text("Notice")
  Text("There is no one there to decend to.")
  Text("The player was moving\nand could not be tracked.")
  Text("The player was hiding indoors\nand could not be tracked.")
  Text("Couldn't decend successfully.")
  Text("All players have logged out.")
  Text("%s has opened.")
  Text("The event log is empty.")
  Text("God Move failed.")
  Text("Monsters can't be placed here.")
  Text("No more spells can be placed here.")
  Text("Spells can't be placed here.")
  Text("No one is here yet.")
  Text("Not enough Pow.")
  Text("Couldn't give it more Life.")
  Text("Couldn't give it more Pow.")
  Text("Failed to give more Pow.")
  Text("No one's there.")
  Text("No more monsters can be placed.")
  Text("You can't intervene now.")
  Text("You can't save now.")
  Text("Can't pause during the event.")
  Text("Event ready.\nTalk to Hisuchin in the Park to begin.")
  Text("Select the Quester to lure the Monster.")
  Text("Select the location to place the Monster.")
  Text("Select the target to strike with lightning.")
  Text("Select the character to Revive.")
  Text("Select the character to give Strength.")
  Text("Select the character to restore Life.")
  Text("Select the location to place the chest.")
  Text("Select the Quester to whisper to.")
  Text("You have received a whisper from God.")
  Text("Sent a private whisper to %s.")
  Text("Round base score set to %D%.")
  Text("Are you sure you want to revive %s (%s Pow)?")
  Text("Heaven")
  Text("No one can be kicked.")
  Text("Are you sure you want to kick %s out?\nThey will not be able to rejoin.")
  Text("%s has been kicked.\n(ID: %s)\nThey will not be able to rejoin until this HomeLand ends.")
  Text("IMPORTANT MESSAGE FROM CHUNSOFT")
  Text("Move Cursor")
  Text("BGM")
  Text("Volume")
  Text("Rumble")
  Text("You got a message from the Friend Book.")
  Text("You sent a message with the Friend Book.")
  Text("Message failed to be sent.")
}
Text("Couldn't give.")
Text("It's meant for someone else.")
Text("Can't carry any more.")
Text("Held %s.")
Text("Deep asleep..")
Text("Mouth sealed.")
if (file == SERVER) {
  Text("Logged in and got revived!")
}
Text("All Questers turned into Dracros!")
Text("Formed bond with %s.")
Text("%s disappeared from the Friend Book.")
Text("%s was delivered.")
Text("Received %s.")
Text("It turned to dust and blew away.")
Text("%s turned to dust and blew away.")
