//this block uses special headers for each string
//there are 112 strings in this block
//remember to set the origin before calling this file

TextErrorCode("*Connection failed.\nPlease wait and try again later.")
TextErrorCode("*System error.\nConnection failed.")
TextErrorCode("*System error.\nConnection failed.")
TextErrorCode("*System error.\nConnection failed.")
TextErrorCode("*Connection refused.\nPlease wait and try again later.")
TextErrorCode("*Connection failed.\nRoute to the server is unknown.")
TextErrorCode("*Could not connect to the server.\nPlease wait and try again later.")
TextErrorCode("*A timeout occurred when trying to connect to the server.")
TextErrorCode("*Connection failed because an invalid request was sent.")
TextErrorCode("Connection canceled.")
TextErrorCode("*The device is in an unrecoverable state.\nPlease wait and try again later.")
TextErrorCode("*NETERR_AT_ERR_TASK")
TextErrorCode("*NETERR_AT_ERR_BUFFS")
TextErrorCode("*Memory pool error.\nPlease turn the power off, restart, and then try again.")
TextErrorCode("*The server is busy.\nPlease wait and try again later.")
TextErrorCode("*NETERR_AT_ERR_UCB")
TextErrorCode("*NETERR_AT_ERR_ICB4")
TextErrorCode("*NETERR_AT_ERR_ICB6")
TextErrorCode("*NETERR_AT_ERR_RT4")
TextErrorCode("*NETERR_AT_ERR_RT6")
TextErrorCode("*NETERR_AT_ERR_IP4")
TextErrorCode("*NETERR_AT_ERR_IP6")
TextErrorCode("*NETERR_AT_ERR_AL4")
TextErrorCode("*NETERR_AT_ERR_AL6")
TextErrorCode("*NETERR_AT_ERR_ARP")
TextErrorCode("*NETERR_AT_ERR_NDP")
TextErrorCode("*Failed to obtain interface number.\nPlease wait and try again later.")
TextErrorCode("*NETERR_AT_ERR_LPB")
TextErrorCode("*NETERR_AT_ERR_DIX")
TextErrorCode("*NETERR_AT_ERR_PPP")
TextErrorCode("*Device error.\nBroadband Adapter is not connected.")
TextErrorCode("*Connection failed.\nNetwork settings may be incorrect.")
TextErrorCode("*Connection failed.\nPlease wait and try again later.")
TextErrorCode("*Connection failed.\nPlease wait and try again later.")
TextErrorCode("*Connection failed.\nServer not found.")
TextErrorCode("*Connection failed because the connection request timed out.\nPlease wait and try again later.")
TextErrorCode("*No response from server.\nPlease wait and try again later.")
TextErrorCode("Connection canceled.")
TextErrorCode("*Connection to server lost.")
TextErrorCode("*System error.\nConnection to server lost.")
TextErrorCode("*Cannot log in to server.\nNetwork settings may be incorrect.")
TextErrorCode("Server is currently unavailable.\nPlease wait and try again later.")
TextErrorCode("Server is currently unavailable.\nPlease wait and try again later.")
TextErrorCode("No more players can enter.\nPlease select another HomeLand.")
TextErrorCode("*The same player already exists.\nMultiple logins are not allowed.")
TextErrorCode("*The same player already exists.\nMultiple logins are not allowed.")
TextErrorCode("A Quester exists with the same name.\nPlease choose a character to distinguish them.")
TextErrorCode("Data was not saved on server last time.\nSelect \"Mascot Retrieval\" from home,\nand select HomeLand again.")
TextErrorCode("You are unable to enter.\nPlease try again in about 5 minutes.")
TextErrorCode("You are no longer able to enter this HomeLand.\nPlease select another HomeLand.")
TextErrorCode("This HomeLand is currently paused.\nLogin failed.")
TextErrorCode("*The same player is already logged in.\nMutltiple logins are not allowed.\nPlease wait and try again later.")
TextErrorCode("*The Account ID matches the game server's Account ID.\nPlease connect again with different data.")
TextErrorCode("The password is incorrect.\nPlease enter again.")
TextErrorCode("You can no longer enter this HomeLand.\nPlease select another HomeLand.")
TextErrorCode("Do not open the Disc Cover while online.\nCommunication lost.")
TextErrorCode("A disc error has occurred.\nCommunication lost.")
TextErrorCode("Communication lost.\nDo not remove the Memory Card while online.")
TextErrorCode("Communication lost.\nA Memory Card error has occurred.")
TextErrorCode("Communication lost.\nThe network cable may not be plugged in.")
TextErrorCode("Trying to disconnect.")
TextErrorCode("Disconnect successful.")
TextErrorCode("You have been kicked out by a God and cannot re-enter.")
TextErrorCode("You have been kicked out by a God and cannot log in.")
TextErrorCode("You have been disconnected from the Matching Server. If you have a problem, please wait and try again later.")
TextErrorCode("*There is no account on the Matching Server.")
TextErrorCode("*The Matching Server is full. Please contact user support.")
TextErrorCode("*Failed to publish HomeLand. From home, select \"Destroy HomeLand\" and create your HomeLand again.")
TextErrorCode("*Failed to publish HomeLand. Please review your router and firewall settings.")
TextErrorCode("*Failed to publish HomeLand. From home, select \"Destroy HomeLand\" and create your HomeLand again.")
TextErrorCode("Failed to publish HomeLand.\nYou cannot restore a HomeLand until after one hour since you left it.")
TextErrorCode("This HomeLand is currently suspended.")
TextErrorCode("The HomeLand you were in is no longer there.\nFrom your home, select \"Mascot Retrieval\"\nand select a new HomeLand.")
TextErrorCode("*It appears you cannot become a God.\nPlease review your router and firewall settings.")
TextErrorCode("*System error.\nAn unpublished HomeLand has been updated.")
TextErrorCode("*System error.\nAn unpublished lobby has been updated.")
TextErrorCode("You have attempted to leave a HomeLand that has not been published.\nPlease contact user support.")
TextErrorCode("*Attempted to leave a published HomeLand.")
TextErrorCode("*There are no Matchmaking Servers available.\nPlease wait and try again later.")
TextErrorCode("Please wait until the beta test begins.")
TextErrorCode("*The request to the Matchmaking Server failed.")
TextErrorCode("Disconnected from the Matchmaking Server.\nPlease wait and reconnect later.")
TextErrorCode("Disconnected from the Matchmaking Server.\nYou can continue playing.")
TextErrorCode("The Matchmaking Server is undergoing maintenence.\nCheck out the DOL Translations Discord for details.")
TextErrorCode("The Matchmaking Server is being prepared for online play.\nPlease wait until the service starts.")
TextErrorCode("Unknown Matchmaking Server error.")
TextErrorCode("Unknown error.")
TextErrorCode("Success")
TextErrorCode("*Library not init.")
TextErrorCode("*Already running.")
TextErrorCode("*Invalid network type.")
TextErrorCode("*Callback function aborted.")
TextErrorCode("*Failed to set MTU.")
TextErrorCode("*Failed to start interface.")
TextErrorCode("*Failed to init.")
TextErrorCode("*Failed to connect.")
TextErrorCode("*Cannot make call.")
TextErrorCode("*Cannot make next call.")
TextErrorCode("*Busy.")
TextErrorCode("Please ensure a LAN cable is connected to the Broadband Adapter.")
TextErrorCode("*Connection failed.\n(LCP negotiation error.)")
TextErrorCode("*Connection failed.\n(IPCP negotiation error.)")
TextErrorCode("Authentication failed.\nPlease re-enter your ISP credentials and try again.")
TextErrorCode("*Connection failed.\nCould not connect within the timeout period.")
TextErrorCode("*Connection failed.\nAccess concentrator not found.")
TextErrorCode("*Connection failed.\nAn error occurred during discovery.")
TextErrorCode("Failed to obtain address from DHCP.\nPlease review your ISP credentials and try again.")
TextErrorCode("An unknown error occurred.")
TextErrorCode("*Network init not performed.")
TextErrorCode("*Modem not supported.\nPlease use a Broadband Adapter.")
TextErrorCode("*Unable to open listening port.\nPlease review your router and firewall settings.")
TextErrorCode("Unknown error code.")
