//there are 370 strings in this block
//remember to set the origin before calling this file

Text("Unknown")
Text("Test Knife")
Text("Strong Test Knife")
Text("Weak Test Knife")
Text("Twig")
Text("Oak Stick")
Text("Bamboo Rod")
Text("Club")
Text("Imitation Wand")
Text("Fan")
Text("Stick of Magic")
Text("Mallet")
Text("Sword")
Text("Stone Axe")
Text("Apprentice Wand")
Text("Double Punch")
Text("Magic Wand")
Text("Big Mallet")
Text("Sharp Axe")
Text("Fighting Glove")
Text("Silencing Wand")
Text("Painful Cudgel")
Text("Cool Fan")
Text("Stick of Light")
Text("Claws")
Text("Battle Axe")
Text("Lightning Staff")
Text("Warrior Sword")
Text("Fire Curse Staff")
Text("Savage Cudgel")
Text("Critical Knife")
Text("Hatchet")
Text("Peacock Fan")
Text("Earth Staff")
Text("Poison Claw")
Text("Steel Axe")
Text("Electric Knuckle")
Text("Mighty Hatchet")
Text("Noble Sword")
Text("Deadly Claw")
Text("Training Knife")
Text("Swinging Sword")
Text("Boru Sword")
Text("Big Hammer")
Text("Ultimate Fan")
Text("Punching Fist")
Text("Violent Axe")
Text("Demon Club")
Text("Life Blade")
Text("Power Blade")
Text("Brave Saber Sm")
Text("Brave Saber")
Text("Royal Sword")
Text("Secret Sword")
Text("Test Shield")
Text("Strong Test Shield")
Text("Weak Test Shield")
Text("Hide Shield")
Text("Scrap Shield")
Text("Rock Shield")
Text("Steel Shield")
Text("Wax Shield")
Text("Gong Shield")
Text("Magic Shield")
Text("Glass Shield")
Text("Slumber Drum")
Text("Spiked Shield")
Text("Dart Shield")
Text("Speed Shield")
Text("Spirit Shield")
Text("Feint Shield")
Text("Gear Shield")
Text("Glare Shield")
Text("Antidote Shield")
Text("Blessing Shield")
Text("NobleShield") //fix later
Text("High-Tech Shield")
Text("Power Shield")
Text("Weathervane")
Text("Warm Shield")
Text("Aluminum Shield")
Text("Dragon Plating")
Text("Light Wood Shield")
Text("Royal Shield")
Text("Brave Shield Sm")
Text("Brave Shield")
Text("Necklace")
Text("Warrior Necklace")
Text("Ruby Necklace")
Text("Cross")
Text("Curse Necklace")
Text("Coral Badge")
Text("Jade Badge")
Text("Fang Badge")
Text("Cool Pendant")
Text("Cyclone Badge")
Text("Hunter Badge")
Text("Jade Pendant")
Text("Blue Sky Badge")
Text("Fang Pendant")
Text("Cyclone Pendant")
Text("Coral Pendant")
Text("Penance Symbol")
Text("Warm Brooch")
Text("Hunter Pendant")
Text("Undeafening Amulet")
Text("Vision Amulet")
Text("Purity Crest")
Text("Green Feather")
Text("Loose Amulet")
Text("Aroma Badge")
Text("Leak Seal")
Text("Unsealable Amulet")
Text("Magic Ring")
Text("Erudorora Ring")
Text("Jade Medal")
Text("Fang Medal")
Text("Cyclone Medal")
Text("Backpack")
Text("Money")
Text("Revival Stone D")
Text("Revival Stone")
Text("Herbs")
Text("Restore")
Text("Restore S")
Text("Water of Life")
Text("Healing Shower")
Text("Tomachu")
Text("Pow-Yan Seeds")
Text("Dried Pow-Yan")
Text("Pow-Yan Concentrate")
Text("Gonzo Medicine")
Text("Golem Ball")
Text("Poison Ball")
Text("Magma Ball")
Text("Ice Ball")
Text("Electric Ball")
Text("Love Ball")
Text("Ace's Sleeve")
Text("Antidote Herb")
Text("Cure-All")
Text("Wind-Glide Wings")
Text("Tobitto Weed")
Text("Guidance of Light")
Text("Emergency Badge")
Text("Friends List")
Text("Silver Bell")
Text("Boomerang")
Text("Bluemerang")
Text("Whitemerang")
Text("Humblemerang")
Text("Royalmerang")
Text("Garlic")
Text("Iron Essence")
Text("Copper Essence")
Text("Silver Essence")
Text("Gold Essence")
Text("Platinum Essence")
Text("Diamond Essence")
Text("Silver")
Text("Gold")
Text("Platinum")
Text("Diamond")
Text("Activity Logger")
Text("__________")
Text("Red Card")
Text("White Card")
Text("Green Card")
Text("Peach Card")
Text("Sticky Paper")
Text("5 Life Points")
Text("Life Points")
Text("Civil Guidebook")
Text("Ancient Essence")
Text("Senden Flyer")
Text("Tama Food Delivery")
Text("Tama Food Delivery")
Text("Tama Food Delivery")
Text("Food Receipt")
Text("Food Receipt")
Text("Food Receipt")
Text("Mystery Box")
Text("Mystery Box")
Text("Sacred Light")
Text("Face of a Man")
Text("Lottery Quiz")
Text("Sign of Royalty")
Text("Stone Key")
Text("__________")
Text("Arjiji Key")
Text("Gang Testimony")
Text("Signed Receipt")
Text("Signed Receipt")
Text("Signed Receipt")
Text("Reailty Chime")
Text("Horse Horn")
Text("Horse Horn")
Text("Croro Key")
Text("Wonder Vase")
Text("Flower Garden Soil")
Text("Broken Poruka Flute")
Text("Spa Water")
Text("Kanel Key")
Text("Kanel Medicine")
Text("Letter from Kimi")
Text("Pure Water")
Text("Beautiful Ring")
Text("Kiro Key")
Text("Whale Conch")
Text("Croats Key")
Text("Parcel")
Text("Parcel")
Text("Parcel")
Text("Powdered Amber")
Text("Amber Receipt")
Text("Sponsor's Request")
Text("Abacus")
Text("Earth Essence")
Text("Treasure Chest Key")
Text("Soul Fragment")
Text("Soul Fragment")
Text("Soul Fragment")
Text("Soul Fragment")
Text("Soul Fragment")
Text("Soul Fragment")
Text("Tama's Signature")
Text("Wing Fragment")
Text("Large Jewel")
Text("Tool Shop Sign")
Text("Dummi's Mirror")
Text("Fake Boron Parts")
Text("Neuron IC")
Text("Wonder Vase")
Text("Nomusan's Favorite")
Text("Banaba's Room Key")
Text("Palmalla Key")
Text("Palmalla Soil")
Text("Hammer")
Text("Tomachu Surprise")
Text("Flowerpot")
Text("Toy Block")
Text("Picture")
Text("Velvera's Jewel")
Text("Knife")
Text("Treasury Pass")
Text("Shrine Doll")
Text("Polka Key")
Text("Polka Flute")
Text("Polka Flute")
Text("Boron Parts")
Text("Devil's Amber")
Text("Origin of Magic")
Text("Mugensou Essence")
Text("Crest Fragment")
Text("Crest Fragment")
Text("Crest Fragment")
Text("Crest Fragment")
Text("Crest Fragment")
Text("Burning the Sea")
Text("Darkness Curse 1")
Text("Darkness Curse 2")
Text("Darkness Curse 3")
Text("Darkness Curse 4")
Text("Dream Chime")
Text("Dirty Ring")
Text("Half-Read Book")
Text("Unreadable Book")
Text("Love Letter")
Text("Prison Key")
Text("Giraffe Key")
Text("Cat Key")
Text("Mouse Key")
Text("Fox Key")
Text("Raccoon Key")
Text("Sparrow Key")
Text("Panda Key")
Text("Cow Key")
Text("Sheep Key")
Text("Goat Key")
Text("Tur-Key")
Text("Camel Key")
Text("Gopher Key")
Text("Owl Key")
Text("Tiger Key")
Text("Dog Key")
Text("Hippo Key")
Text("Rabbit Key")
Text("Leopard Key")
Text("_________")
Text("Mountain Key")
Text("Blue Turtle")
Text("Abram's Sign")
Text("Cyphered Text")
Text("Healing Flower")
Text("Delivery")
Text("Blacksmith Hammer")
Text("Wind Charm")
Text("Wind Message")
Text("Kanel Medicine")
Text("Library Book")
Text("Kuro's Gift")
Text("Small Key")
Text("Golbo's Bottle")
Text("Golbo's Bottle")
Text("Key")
Text("Jewelry Box")
Text("Jewelry Box")
Text("Warehouse Key")
Text("Gentle Breeze")
Text("Shears")
Text("Hero's Sword")
Text("Hero's Shield")
Text("Pachinko Ball")
Text("Paren Juice")
Text("Bandage")
Text("Clear Water")
Text("Old Wood Shield")
Text("Old Wood Bow")
Text("Engagement Ring")
Text("Friend Badge")
Text("Rock Plate")
Text("Old Mirror")
Text("Sky Blue Bracelet")
Text("Rusty Key")
Text("Mirror")
Text("Mirror")
Text("Introduction")
Text("Broken Horse Bell")
Text("Horse Bell")
Text("Large Horn")
Text("Delivery")
Text("Comms. Card")
Text("Letter to Kira")
Text("Ruin Clue")
Text("Pickaxe")
Text("Treasure")
Text("Small Ring")
Text("Tiny Soul")
Text("Meat Soul")
Text("Nail Soul")
Text("Bread Soul")
Text("Paper Soul")
Text("Pencil Soul")
Text("Letter Soul")
Text("Fire Soul")
Text("Bag")
Text("Omenger Card")
Text("Super Card")
Text("Hero Card")
Text("Secret Card")
Text("Kick Card")
Text("Special Card")
Text("Support Card")
Text("Hand Card")
Text("Red Card")
Text("Blue Card")
Text("Yellow Card")
Text("Green Card")
Text("Pink Card")
Text("Master Card")
Text("Robo Card")
Text("Fake Out Card")
Text("Boss Card")
Text("Big Bad Card")
Text("Evil Card")
Text("Weak Card")
Text("Ultra Rare Card")
Text("Prime Trick")
Text("Water Key")
Text("Water Key")
