//there are 142 strings in this block
//remember to set the origin before calling this file

Text("Kari")
Text("Croats Village")
Text("Croats Field")
Text("Pure Spring")
Text("Spring Cave")
Text("Tokoyami Depths")
Text("Tokoyami Cave")
Text("Horo Forest")
Text("Horo Forest Depths")
Text("Kanel Field")
Text("Kanel Peninsula")
Text("Kanel Road")
Text("Rainbow Ruins")
Text("Healing Forest")
Text("Deep Forest")
Text("Forest Cave 1F")
Text("Forest Cave 2F")
Text("Cave Depths")
Text("Tough Forest 1F")
Text("Tough Forest 2F")
Text("Kanel Town")
Text("Kanel Library 1F")
Text("Kanel Library 2F")
Text("Kanel Library B1")
Text("Kanel Library Underpass")
Text("Tunnel Kanel Side")
Text("Underground Library")
Text("Tunnel Croro Side")
Text("Croro Ruins")
Text("Croro Maze Entrance")
Text("Croro Maze 1F")
Text("Croro Maze 2F")
Text("Croro Maze 3F")
Text("Croro Maze 4F")
Text("Croro Maze 5F")
Text("Croro Maze 6F")
Text("Croro Maze 7F")
Text("Croro Maze 8F")
Text("Illumina Road")
Text("Friend Shrine")
Text("Illumina Town")
Text("Wind Cape")
Text("Kiro Town")
Text("Haunted House")
Text("Kiro Field")
Text("Kiro Cliffs")
Text("Kiro Swamp")
Text("Erudorora")
Text("Valk Road")
Text("Kiro Road")
Text("Apricant Road")
Text("Kiro Mine Ruins")
Text("Kiro Mine 1F")
Text("Kiro Mine 2F")
Text("Kiro Mine 3F")
Text("Kiro Mine 4F")
Text("Great Hall")
Text("Kiro Mine Depths")
Text("Applicant Field")
Text("Palmalla Field")
Text("Valley of Kings")
Text("Googoo's Cave 1F")
Text("Googoo's Cave 2F")
Text("Apricant")
Text("Little Apricant")
Text("Apricant Warehouse")
Text("Apricant Tower")
Text("Little Maze")
Text("Palmalla")
Text("Trek Mountain")
Text("Escape Route 1F")
Text("Escape Route 2F")
Text("Escape Route 3F")
Text("Trek Mountainside")
Text("Trek Mountain 5F")
Text("Trek Mountain 6F")
Text("Trek Mountain 7F")
Text("Trek Mountain Peak")
Text("Polka Road")
Text("Polka Forest North")
Text("Polka Forest South")
Text("Polka Village")
Text("Polka Cape")
Text("Accident Area")
Text("Valk Desert")
Text("Bandit Hideout")
Text("Desert Ruins 1F")
Text("Desert Ruins 2F")
Text("Ritual Hall")
Text("Valk Town")
Text("Valk Castle")
Text("Entrance")
Text("Audience Hall")
Text("Money Vault")
Text("Rao Dungeon")
Text("Secret Path")
Text("Cocotto Forest")
Text("Cocotto Village Gate")
Text("Cocotto Village")
Text("Zargus Cave")
Text("Zargus Hall")
Text("Elza")
Text("Elza Entrance")
Text("Elza Hall")
Text("Control Room")
Text("Elza Tower 1F")
Text("Elza Tower 2F")
Text("Elza Tower 3F")
Text("Elza Tower 4F")
Text("Elza Tower 5F")
Text("Elza Tower 6F")
Text("Elza Tower 7F")
Text("Elza Tower 8F")
Text("Elza Tower 9F")
Text("Elza Tower 10F")
Text("Romsite")
Text("Romsite Interior")
Text("Remuru")
Text("Professor House")
Text("Remuru Valley 1F")
Text("Remuru Valley 2F")
Text("Remuru Valley 3F")
Text("Remuru Valley 4F")
Text("Whale Isle")
Text("Dream World")
Text("Dream World Road")
Text("Dream Hall")
Text("Dream World Road, Sky-Blue")
Text("Dream World Road, Yellow")
Text("Dream World Road, Blue")
Text("Dream World Road, Purple")
Text("Dream World Road, Red")
Text("Dream World Road, Green")
Text("Dream World Road Entrance")
Text("Mugensou Cave 1F")
Text("Mugensou Cave 2F")
Text("Mugensou Cave 3F")
Text("Drakuro Castle")
Text("The Ark")
Text("Quester Park")
Text("Big God Hall")
Text("King Drakuro's Hall")
