//there are 30 strings in this block
//remember to set the origin before calling this file

Text("Block")
Text("Flame")
Text("Sparkle")
Text("Polka")
Text("Pinnoc")
Text("Eggpot")
Text("Cyclone")
Text("Doh")
Text("Mystica")
Text("Robot")
Text("Gort")
Text("Unicorn")
Text("Tiptap")
Text("Paradisa")
Text("God")
//Text("They build to release their power.")
//Text("Fire tribes that can use various powers.")
//Text("Gem tribes that create barriers to block spells.")
//Text("Green tribes that are good at drawing out the power of the earth.")
//Text("Doll tribes that can heal wounds and poisons well.")
//Text("Egg tribes that hide in their shells and release their powers.")
//Text("Typhoon tribes that can use the wind to blow and spit.")
//Text("Clay tribes that can change shape and transform in various ways.")
//Text("Invisible tribes that can deceive enemies by becoming invisible.")
//Text("Robot tribes that are good at manipulating tools.")
//Text("They can see through buildings with guts and physical strength.")
//Text("A swordsman like a swift breeze.")
//Text("They use antennas An insect tribe that shoots electricity.")
//Text("A mysterious squid tribe with strange eyes.")
//Text("An entity of the human race (necessary for playing as a god).")
