//there are 39 strings in this block
//remember to set the origin before calling this file

Text("Area:")
Text("Zip:")
Text("Name:")
Text("Mascot:")
Text("Time: ") //elapsed:")
Text("Password:")
Text("Priority:")
Text(" ")
Text("Confirm")
Text("Return")
Text("Search this region for a HomeLand GameCube.")
Text("Search by distance to adventure.")
Text("Search by name of God player.")
Text("Search by number of players in the adventure.")
Text("Search by time passed since the adventure began.")
Text("Search by password protected.")
Text("Search by keyword.\nDisplays first 50 results.")
Text("Search by keyword.")
Text("Return to your room without searching for a HomeLand.")
Text("Nearby")
Text("Any")
Text("Same Region")
Text("closest nearby")
Text("5 players or less")
Text("10 players or less")
Text("More than 10 players")
Text("More than 20 players")
Text("More than 30 players")
Text("About to start")
Text("Around 1 hour left")
Text("Around 5 hours left")
Text("Around 10 hours left")
Text("Yes")
Text("No")
Text("Number of players")
Text("Number of total players")
Text("World uptime")
Text("Number of guiding forces")
Text("%s %s")
