//there are 501 strings in this block
//remember to set the origin before calling this file

Text("Haru")
Text("Bibi")
Text("Ruki")
Text("Super R") //Super Ruki
Text("Yuon")
Text("Barakina")
Text("Dota")
Text("Guren")
Text("Pokocha")
Text("Bo")
Text("Fu")
Text("Kururu")
Text("Pot Spirit")
Text("Boen")
Text("Neru")
Text("Azeru")
Text("Jiku")
Text("Perselk")
Text("Golem")
Text("Poison") //Golem")
Text("Electric") // Golem")
Text("Magma") // Golem")
Text("Ice") // Golem")
Text("Love Golem")
Text("unused")
Text("unused")
Text("Nickela")
Text("Galliume")
Text("Lithiumus")
Text("Cobalto")
