//there are 48 strings in this block
//remember to set the origin before calling this file

Text("? ? ? ? ?")
Text("Whisper")
Text("Thunder")
Text("Great Thunder")
Text("Royal Thunder")
Text("Gather Mon") //Gather Monster
Text("Summon Monster")
Text("Hercules' Fists")
Text("Healing Light")
Text("Revival Thread")
Text("Healing Chest")
Text("Curing Chest")
Text("Vitality Chest")
Text("Monster Chest")
Text("Earth Incarn.")
Text("Stone Incarn.")
Text("Poison Incarn.")
Text("Thunder Incarn.")
Text("Magma Incarn.")
Text("Ice Incarn.")
Text("Love Incarn.")
Text("Evil Incarn.")
Text("Start Jintori")
Text("Start Prison Break")
Text("Whisper to someone.")
Text("Cast thunder.")
Text("Cast powerful thunder.")
Text("Cast very powerful thunder.")
Text("Attract Monsters to the Quester.")
Text("Summon a Monster.")
Text("Grant Power.")
Text("Recover Life.")
Text("Revive someone.")
Text("Place a Healing Treasure Chest.")
Text("Place a Curing Treasure Chest.")
Text("Place a Vitality Treasure Chest.")
Text("Place a Monstrous Treasure Chest.")
Text("Summon Golem.")
Text("Summon Stone Golem.")
Text("Summon Poison Golem") //.
Text("Summon Thunder Golem.")
Text("Summon Magma Golem.")
Text("Summon Ice Golem.")
Text("Summon Love Golem.")
Text("Summon Evil Golem.")
Text("Begin Jintori scenario.")
Text("Begin Elza: Prison Break scenario.")
if (file == ALONE) {
  Text("Starting Point")
}
