//there are 353 strings in this block
//remember to set the origin before calling this file

Text("Bug")
Text("Unreliable")
Text("Leave the World")
Text("Return to Earth")
Text("Shout Loudly")
Text("Bless")
Text("Heal")
Text("Complete Heal")
Text("Healing Glow")
Text("Healing Light")
Text("Resurrect")
Text("Purify")
Text("Meditation")
Text("Book of Str")
Text("Book of Speed")
Text("Book of Mind")
Text("Book of Power")
Text("Book of Exp")
Text("Physical Guard")
Text("Tremble Guard")
Text("Fear Guard")
Text("Confuse Guard")
Text("Sleepy Guard")
Text("Silence Guard")
Text("Smash")
Text("Guts")
Text("Spirit")
Text("Blow")
Text("Big Blow")
Text("Hurricane")
Text("Inhale")
Text("Item Crane")
Text("Transfer")
Text("Listening")
Text("Treasure Echo")
Text("P-Wave")
Text("Disturbing Wave")
Text("Confusing Wave")
Text("Item Fusion")
Text("Item Duplicate")
Text("Sword")
Text("Spin Cutter")
Text("Air Sword")
Text("Reflect Barrier")
Text("Reflect Barrier 3")
Text("Reject Barrier")
Text("Reject Barrier 3")
Text("Expand Barrier")
Text("Super Barrier")
Text("Release Barrier")
Text("Green Heal")
Text("Bathing")
Text("Life Blessing")
Text("Water Bullet")
Text("Earth Dust")
Text("Mimic Enemy")
Text("Mimic Distant Enemy")
Text("Mimic Thing")
Text("Mimic Chest")
Text("Mimic Human")
Text("Mimic Monster Friend")
Text("Mimic Form")
Text("Turn Back")
Text("Hide")
Text("Turn Invisible")
Text("Show True Form")
Text("Invert Vision")
Text("Move Space")
Text("Swap Space")
Text("Attract")
Text("Swap Multiple")
Text("Release One")
Text("Release All")
Text("East")
Text("West")
Text("South")
Text("North")
Text("Seal Text")
Text("Shout!!")
Text("Fake Ailment")
Text("Smelly Gel")
Text("Sticky Gel")
Text("Sour Gel")
Text("Countdown Eruption")
Text("Flame")
Text("Wildfire")
Text("Freeze")
Text("Frozen Wave")
Text("Nullify Attack")
Text("Unbind")
Text("Visible")
Text("Phase")
Text("Earthquake Roar")
Text("Paralyze Roar")
Text("Power Up")
Text("2nd Attack")
Text("Fire Combo")
Text("Light Combo")
Text("Wind Combo")
Text("Stop Holding")
Text("Break Up Group")
Text("Lower Guard")
Text("Remove Status")
Text("Poison Slam")
Text("Deadly Slam")
Text("Fire Slam")
Text("Light Slam")
Text("Ice Slam")
Text("Sure Slam")
Text("Blowing Slam")
Text("Double Lariat")
Text("Use Item")
Text("Unequip")
Text("Steal")
Text("Confuse Gas")
Text("WideConfuse Gas")
Text("Blind Gas")
Text("WideBlind Gas")
Text("WideSleep Gas")
Text("WideSlilence Gas")
Text("WidePoison Gas")
Text("WideDeadly Gas")
Text("Ink Goo")
Text("Copy Strength")
Text("Copy Speed")
Text("Copy Mind")
Text("Reflect Spell")
Text("Lower Stats")
Text("Recover")
Text("Nanto Suichouken")
Text("Slash")
Text("Beam")
Text("Circular Strike")
Text("Flash")
Text("Jumbo Laser")
Text("Call Allies")
Text("Excite")
Text("Retreat")
Text("Rock Drop")
Text("Volcano")
Text("Break")
Text("Trade Life")
Text("Dark Wave")
Text("Boom")
Text("Meteor Kick")
Text("Wear Veil")
Text("Target Enemy")
Text("Move")
Text("Hurricane")
Text("Thunder")
Text("Great Thunder")
Text("Royal Thunder")
Text("Strength Up")
Text("Healing Wind")
Text("Resurrect Crown")
Text("Large Clothes")
Text("Small Clothes")
Text("Sum")
Text("Escape")
Text("Pu")
Text("Puyu")
Text("Puyuton")
Text("Puyuna")
Text("Puyutana")
Text("Ho")
Text("Hono")
Text("Honon")
Text("Hodon")
Text("Honodon")
Text("I")
Text("Izu")
Text("Izna")
Text("Gizna")
Text("Gizazna")
Text("Ra")
Text("Raa")
Text("Ku")
Text("Kuu")
Text("Kuuga")
Text("Ze")
Text("Zero")
Text("Zeros")
Text("Mizero")
Text("Mizeros")
Text("Kyu")
Text("Kyupo")
Text("Wu")
Text("Wupa")
Text("Tap")
Text("Pip")
Text("Chip")
Text("Tahena")
Text("Tahenan")
Text("Pihena")
Text("Pihenan")
Text("Chihena")
Text("Chihenan")
Text("Know")
Text("Knowchi")
Text("Hyah")
Text("Zuzu")
Text("Chako")
Text("Noro")
Text("Sara")
Text("Sarasa")
Text("Rulero")
Text("Boo")
Text("Escape")
Text("Go Home")
Text("Gyun")
Text("Interact with Zone")
Text("Move to Zone")
Text("Idegomu")
Text("Para")
Text("Dracron")
Text("unused")
Text("unused")
Text("unused")
Text("unused")
Text("unused")
Text("unused")
Text("unused")
Text("unused")
Text("unused")
Text("unused")
Text("Return to earth and hide.")
Text("Shout with a loud voice!")
Text("Restore Life.")
Text("Greatly restore life.")
Text("Completely restore Life.")
Text("Restore Life in small area.")
Text("Restore Life in a large area.")
Text("Revive an enemy.")
Text("Cure all status effects.")
Text("Recover your Power.")
Text("Share some Strength.")
Text("Share some Speed.")
Text("Share some Mind.")
Text("Share some Power.")
Text("Share some Experience.")
Text("Hide inside shell to absorb damage.")
Text("Make attacking enemies Trembled.")
Text("Make attacking enemies Rooted.")
Text("Make attacking enemies Confused.")
Text("Make attacking enemies Sleepy.")
Text("Make attacking enemies Silenced.")
Text("Break guard with strong attack.")
Text("Increase Power.")
Text("Greatly increase Power.")
Text("Blow.")
Text("Blow great damage.")
Text("Blow damage around.")
Text("Pull an enemy.")
Text("Steal an item from a distant enemy.")
Text("Send an item to a distant player.")
Text("Increase hearing significantly.")
Text("Search for treasure.")
Text("Confuse nearby enemies.")
Text("Confuse surrounding enemies.")
Text("Confuse all surrounding enemies.")
Text("Combine items to make new ones.")
Text("Copy an item using money.")
Text("Guaranteed hit in a single blow.")
Text("Attacks all around at once (needs checking)")
Text("Attacks far away (needs checking)")
Text("Create a barrier to reflect spells.")
Text("Create 3 Reflect barriers.")
Text("Create a barrier to block spells")
Text("Create 3 Block barriers.")
Text("Create a barrier to spread spells.")
Text("Create a barrier to greatly spread spells.")
Text("Remove all barriers.")
Text("Restore Life with the power of grass.")
Text("Fully restore Life with the power of grass.")
Text("Revive with grass.")
Text("unused")
Text("Kick the dirt to Blind.")
Text("Morph to enemy.")
Text("Morph to distant enemy.")
Text("Morph to physical object.")
Text("unused")
Text("unused")
Text("unused")
Text("unused")
Text("Turn back to normal form.")
Text("unused")
Text("Hide self form.")
Text("Hide another form.")
Text("Show true form.")
Text("Continue seeing invisible objects.")
Text("unused")
Text("unused")
Text("Fly to a distant town.")
Text("unused")
Text("Revive with grass.")
Text("Blow away large rocks.")
Text("Blow away rocks.")
Text("Bring rocks closer.")
Text("Escape to safety.")
Text("Attacks all surrounding enemies")
Text("Restore some Life.")
Text("Restore Life.")
Text("Greatly restore Life.")
Text("Restore Life of multiple allies.")
Text("Restore Life of all allies.")
Text("Flame an ememy.")
Text("Big flame an enemy.")
Text("Pow flame an enemy.")
Text("Flame a distant ememy.")
Text("Big flame an distant enemy.")
Text("Lightning attack 2 distant enemies.")
Text("Lightning attack 2 distant enemies.")
Text("Lightning attack 3 distant enemies.")
Text("Lightning attack 4 distant enemies.")
Text("Lightning attack all distant enemies.")
Text("Revive an ally to partial Life.")
Text("Revive an ally to full Life.")
Text("Blow close enemies.")
Text("Strong blow enemies.")
Text("Great blow enemies.")
Text("Freeze enemies.")
Text("Strong freeze enemies.")
Text("Deep freeze enemies.")
Text("Freeze distant enemies.")
Text("Deep freeze far enemies.") //fix later
Text("Absorb enemy Life.")
Text("Greatly absorb enemy Life.")
Text("Drain enemy Power.")
Text("Drain all nearby enemy Power.")
Text("Increase Strength temporarily.")
Text("Increase Speed temporarily.")
Text("Increase Mind temporarily.")
Text("Reduce enemy Strength.")
Text("Reduce nearby enemy Strength.")
Text("Reduce enemy Speed.")
Text("Reduce nearby enemy Speed.")
Text("Reduce enemy Mind.")
Text("Reduce nearby enemy Mind.")
Text("Check enemy Life.")
Text("Check nearby enemy Life.")
Text("Make all nearby enemies Rooted.")
Text("Put all enemies to sleep.")
Text("Silence an enemy.")
Text("Slow down all nearby enemies.")
Text("Cure poison.")
Text("Cure strong poison.")
Text("Cure all status effects.")
Text("Reveal hidden characters.")
Text("Escape to a sunlit place when free.")
Text("Go to last visted town when free.")
Text("Charge straight forward.")
Text("unused")
Text("Cast a witch's curse.")
