// System Text

// Start.dol
Text($00115A08, "[ ON  ")
Text("  OFF]")
Text("Settings saved.")
Text("[Save ")
Text("  Reset]")
Text("The Disc Cover is open.\nTo continue the game, please close the Disc Cover.")
Text("Please insert the HOMELAND Game Disc.")
Text("The Game Disc could not be read.\nRead the Instruction Booklet for more information.")
Text("An error has occurred.\nTurn the power off and refer to the Nintendo GameCube Instruction Booklet for further instructions.")
Text("Please wait..")
Text("There is no Memory Card inserted in Slot A.")
Text("There is no Memory Card inserted in Slot A.\nIf you continue, you will not be able to save.")
Text("There is not enough available space in the Memory Card in Slot A.\n1 file and %d blocks are required to save.")
Text("Name could not be set because there is no usable Memory Card in Slot A.\nPlease enter your name again.")
Text("The Memory Card in Slot A is corrupted and must be formatted.\nPreviously saved data will be lost.\nFormat?")
Text("Data on the Memory Card in Slot A\nis corrupted and needs to be formatted.")
Text("Format?")
Text("Format failed.\nThe Memory Card in Slot A is broken and cannot be used.")
Text("Formatted.")
Text("The Memory Card in Slot A is broken and cannot be used.")
Text("Once you start the game, you won't be able to save.")
Text("There was no data from when you started the game on the Memory Card in Slot A,\nso you cannot save.")
Text("There was no data from when you started the game on the Memory Card in Slot A,\nso you cannot load.")
Text("Another device in Slot A. Please insert a Memory Card.")
Text("Failed to save to the Memory Card in Slot A.")
Text("Failed to read from the Memory Card in Slot A.")
Text("Saving your adventure to the Memory Card in Slot A.\nDo not touch the Memory Card or the POWER Button.")
Text("Adventure saved.")
Text("Data is from a different game version. Delete it?")
Text("Memory Card has corrupted data. Format?")
Text("Attempting to repair corrupted HomeLand save on the Memory Card.")
Text("Starting in %2d:%2d\n%2d Players")
Text("Ending in %2d:%2d")
Text("Connect to the network using the Broadband Adapter?")
Text("Connecting to the network.. (Press B to cancel)\nDo not touch the Memory Card or the POWER Button.\nWhen playing online with other players,\nplease exercise courtesy and discretion.\nWe are not responsible for damage caused by online interactions.")
Text("Testing network connection..\nDo not touch the Memory Card or the POWER Button.\nPress the B Button to cancel the connection.")
Text("Connecting to the game server.. (Press B to cancel)\nDo not touch the Memory Card or the POWER Button.\nWhen playing online with other players,\nplease exercise courtesy and discretion.\nWe are not responsible for damage caused by online interactions.")
Text("Connecting to the matching server.. (Press B to cancel)\nDo not touch the Memory Card or the POWER Button.\nWhen playing online with other players,\nplease exercise courtesy and discretion.\nWe are not responsible for damage caused by online interactions.")
Text("Accessing the matching server.\nPlease wait..")
Text("Disconnecting from the network.\nPlease wait..")
Text("Please enter your ISP connection password.")
Text("The PPPoE password was not saved in Network Settings.\nThe password must be re-entered.")
Text("If the PPPoE password is saved in Network Settings,\nyou will not need to re-enter the password later.")
Text("Nintendo is not responsible for any damage caused by misuse of personal authentication information.")
Text("When using the WaveBird (DOL-004) personal information\ncould be leaked to others. Please connect a regular controller (DOL-003)\nto input sensitive information.")
Text("Nintendo is not responsible for any damage caused by use of the WaveBird.")
Text("Please enter the IP Address of the GAMECUBE to connect to.")
Text("Cancel connection attempt?")
Text("%s's HomeLand, which you just visited, has reached its end.")
Text("%s's HomeLand you just selected is no longer there.\nPlease try again.")
Text("The HomeLand you selected is no longer there.\nPlease try again.")
Text("%s's HomeLand has been moved.")
Text("Wait until a HomeLand is found?")
Text("Get notified by Rumble feedback when one is found?")
Text("Searching for the HomeLand you were just playing.\nYou can cancel by pressing the B Button.")
Text("RECEIVED REWARDS:\n")
Text("Received %d Clear Points.")
Text("Learned how to make a %s Mascot.")
Text("Received %s Accessory.")
Text("The History log is empty.")
Text("Shutdown canceled after starting event.")
Text("Save")
Text("Bookmark")
Text("Complete")
Text("Start")
Text("Log Out")
Text("Settings")
Text("Quit")
Text("Save to Memory Card.")
Text("Save to Memory Card. \n2P golems will not be saved,\nand will disappear after you leave.")
Text("Leave your adventure?")
Text("Leave your adventure? You will not be able to save.")
Text("You can't leave here.")
Text("Save adventure and return to your room?")
Text("Save adventure and return to your room?\n2P golems will not be saved,\nand will disappear if you leave.")
Text("Return to your room? (Connection will be lost.)")
Text("It is not safe to save right now!")
Text("Message could not be sent.")
Text("%s could not be cast.")
Text("Cannot send back.")
Text("Couldn't be sent home.")
Text("No one home.")
Text(" Spell")
Text("Just %s.")

//Pause Menu
Text($00116C90, "Save")
Text($00116C9C, "Quit")
Text($00116CD0, "Settings")
Text($00116CE8, "Save to Memory Card?")
Text($00116D08, "Save to Memory Card?")
Text($00116D78, "Save and quit to menu?")
Text($00116DFC, "Would you like to save and return home?")

Text($00199E28, "History")
Text($0019A198, "History")

// start.rel
Text($57051B14, "Are you a boy or a girl?")
Text($57051B44, "Please name your character.")
Text($57051B60, "This name already exists on the Memory Card.")
Text($57051BA0, "Begin your adventure with this name?")
Text($57051BC8, "New adventure data has been saved on the Memory Card.")

Text($57051D18, "%03d hours %02d mins")

Text($57051F54, "Check the Memory Card")
Text($57051F6C, "Manage the Memory Card")
Text($57051F8C, "Continue without save")
Text($57051FBC, "Is it OK to erase this data?")
Text($57051FE0, "Are you sure you want to erase this data?")
Text($570520E8, "Is it OK to erase this data?")
Text($5705210C, "Are you sure you want to erase this data?")
Text($57052168, "Failed to load Memory Card.")

Text($570523A8, "Play Time:")

Text($57052600, "Weapons")
Text($57052608, "Shields")
Text($57052610, "Items")
Text($57052618, "You have %D EXP")
Text($5705262C, "New Game")
Text($57052640, "Online")
Text($57052650, "Network Setup")
Text($57052660, "Connection Test")
Text($57052670, "Credits")
Text($57052684, "Go to Network Settings?")
